// apps/appizza-login/src/app/app.tsx
import { LoginForm } from './components/LoginForm';

import './app.module.scss';

export function App() {
  return (
    <main className="flex flex-col h-screen">
      <ui-header />

      <div className="mb-auto w-10/12 mx-auto my-auto">
        <LoginForm />
      </div>

      <ui-footer name="Appizza" framework="React" />
    </main>
  );
}

export default App;

// apps/appizza-admin/src/app/app.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { HttpClientModule } from '@angular/common/http';

@Component({
  standalone: true,
  selector: 'appizza-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [CommonModule, RouterModule, HttpClientModule],
})
export class AppComponent {}

<main class="flex flex-col h-screen">
  <ui-header />

  <div class="mb-auto w-10/12 mx-auto my-5">
    <router-outlet />
  </div>

  <ui-footer name="Appizza" framework="Angular" />
</main>
